# :nodoc: namespace
module SpStore

# API implemented by a S chip (slow processor that holds state across reboots).
module SChip
  # The second step of the S-P boot sequence.
  #
  # Args:
  #   nonce:: the nonce generated by the P Chip in the first step of the boot
  #           sequence; returned by PChip#boot_start
  #   nonce_hmac:: the nonce HMAC generated by the P chip in the first step of
  #                the boot sequence; returned by PChip#boot_start
  #
  # Returns the following:
  #   * root hash of the storage hash tree
  #   * HMAC of the root hash and the FPGA nonce keyed under the FPGA's
  #     symmetric key, and
  #   * the private endorsement key, encrypted under the FPGA's symmetric key
  #
  # Note: under normal operation, the root hash can also come from untrusted
  #       storage. However, having the card provide it can help the server
  #       recover from a power failure.
  def boot(nonce, nonce_hmac)
    
  end
end  # class SpStore::SChip

end  # namespace SpStore
