# :nodoc: namespace
module SpStore::Mocks

# Software model for the controller that pretends to do security.
class BareController
  # Creates a new mock S-P store controller.
  #
  # Args:
  #   store:: the block store to be served
  #   ca_keys:: keypair for the Certificate Authority
  #   ca_cert:: the CA certificate
  #   keys:: Endorsement Key (a random key is generated by default)
  #   cert:: if given, it is used as an Endorsement Certificate
  def initialize(store, ca_keys, ca_cert, keys = nil, cert = nil)
    @store = store
    @ekeys ||= SpStore::Crypto.key_pair
    controller_dn = {'CN' => 'SP Mock Controller', 'C' => 'US'}
    @ecert ||= SpStore::Crypto.cert controller_dn, 365, ca_keys, ca_cert,
                                    @ekeys[:public]
  end

  def endorsement_certificate
    @ecert
  end

  def session(encrypted_session_key)
    session_key = SpStore::Crypto.pki_decrypt @ekeys[:private],
                                              encrypted_session_key
    Session.new @store, session_key
  end
end  # class SpStore::Mocks::BareController

# :nodoc: namespace
class BareController

# :nodoc: session implementation
class Session
  def initialize(store, session_key)
    @store = store
    @key = session_key
  end
  
  def close
  end
  
  def block_size
    @store.block_size
  end
    
  def blocks
    @store.blocks
  end
  
  def read_block(block_id, nonce)
    data = @store.read_block block_id
    hmac = SpStore::Crypto.hmac_for_block block_id, data, nonce, @key
    return data, hmac
  end

  def write_block(block_id, data, nonce)
    data = @store.write_block block_id, data
    SpStore::Crypto.hmac_for_block block_id, data, nonce, @key
  end
end  # class SpStore::Mocks::BareController::Session
  
end  # namespace SpStore::Mocks::BareController

end  # namespace SpStore::Mocks
